export enum AuditModules {
  AUTH = 'AUTH',
  USER = 'USER',
  PRODUCT = 'PRODUCT',
  CATEGORY = 'CATEGORY',
  CART = 'CART',
  ORDER = 'ORDER',
  REVIEW = 'REVIEW',
  COUPON = 'COUPON',
}

export enum AuditActions {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',

  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REGISTER = 'REGISTER',

  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  CHANGE_ROLE = 'CHANGE_ROLE',
  CHANGE_STATUS = 'CHANGE_STATUS',

  REFRESH_TOKEN = 'REFRESH_TOKEN',
}
